/* Generated by esbuild. Edit src/ instead. */

// src/main.js
var api = sandkit.api;
var logged = false;
function enableAchievements() {
  const integrity = sandkit.engine.state?.store?.integrity;
  if (!integrity) {
    return;
  }
  integrity.modsUsed = false;
  if (!logged) {
    logged = true;
    console.info(
      "[Enable Achievements] active; native achievement checks enabled"
    );
  }
}
api.events.on("mods:initialized", enableAchievements);
api.schedule.nextTick(enableAchievements);
