const path = require("node:path");
const esbuild = require("esbuild");

const modRoot = path.resolve(__dirname, "..");

esbuild.buildSync({
  entryPoints: [path.join(modRoot, "src/main.js")],
  outfile: path.join(modRoot, "main.js"),
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  banner: { js: "/* Generated by esbuild. Edit src/ instead. */" },
});
