/* Generated by esbuild. Edit src/ instead. */

// src/register.js
function registerMod(api, mod) {
  api.i18n.register("en", {
    [`mods|${mod.id}|name`]: mod.name,
    [`mods|${mod.id}|description`]: mod.description
  });
  api.events.on("game:started", () => {
    api.ui.toast(`${mod.name} loaded`);
  });
  console.info(`[${mod.name}] registered`);
}

// src/main.js
var MOD_ID = "paragax.mod-id";
var MOD_NAME = "Mod Name";
var MOD_DESCRIPTION = "Replace with a short description of the mod.";
registerMod(sandkit.api, {
  id: MOD_ID,
  name: MOD_NAME,
  description: MOD_DESCRIPTION
});
