/* Generated by esbuild. Edit src/ instead. */

// src/colors.js
function hueToHex(hue) {
  const h = (hue % 360 + 360) % 360;
  const k = (offset) => (offset + h / 30) % 12;
  const channel = (offset) => Math.round(
    255 * (0.5 - 0.5 * Math.max(-1, Math.min(k(offset) - 3, 9 - k(offset), 1)))
  );
  return channel(0) << 16 | channel(8) << 8 | channel(4);
}
function hexToLightColor(color) {
  return [
    (color >> 16 & 255) / 255,
    (color >> 8 & 255) / 255,
    (color & 255) / 255,
    1
  ];
}

// src/beam-controller.js
function createBeamController(api2, ActionState2, config2, excavationPattern2, itemId, damageUpgradeId, damagePerLevel, thicknessUpgradeId, thicknessPerLevelPercent) {
  const COLOR_CYCLE_MS = 1800;
  const BASE_BEAM_DAMAGE = 1;
  let beamGraphics = [];
  let chargeStartMs = 0;
  let charged = false;
  function destroyBeams() {
    for (const beam of beamGraphics) {
      beam.destroy();
    }
    beamGraphics = [];
  }
  function resetCharge() {
    charged = false;
    chargeStartMs = 0;
  }
  function startCharge(now) {
    charged = false;
    chargeStartMs = now;
    api2.sound.play("charge_up", {
      offset: 1.5,
      volume: 0.2,
      fadeIn: 1.5
    });
    api2.sound.play("charge_up_2", {
      maxDuration: 0.95,
      volume: 0.1
    });
    api2.sound.play("charge_up_3", {
      maxDuration: 1,
      offset: api2.random.float(0.5, 2),
      volume: 0.05,
      fadeIn: 1
    });
  }
  function getBeamFrame(state, now) {
    const player = state.store.player;
    const originX = player.x + player.width / 2;
    const originY = player.y + player.height / 2 + 2;
    const mouse = state.session.input.mouse.worldPosition;
    const aimAngle = Math.atan2(mouse.y - originY, mouse.x - originX);
    const centralHit = api2.raycast.castFromWorld(
      originX,
      originY,
      aimAngle,
      config2.maxRangePx
    );
    if (!centralHit && !charged) {
      chargeStartMs = now;
    }
    const progress = Math.min((now - chargeStartMs) / config2.windupMs, 1);
    charged ||= progress >= 1;
    const smoothProgress = progress * progress * (3 - 2 * progress);
    const spread = config2.maxSpreadRadians * (1 - smoothProgress);
    const spin = progress * Math.PI * 4;
    const baseWidth = progress < 1 ? 1 + 2 * progress : 3;
    const thicknessLevel = api2.upgrades.getLevelById(
      itemId,
      thicknessUpgradeId
    );
    const width = baseWidth * (1 + thicknessPerLevelPercent / 100 * thicknessLevel);
    const brightness = progress < 1 ? 0.1 + 0.4 * progress : 1;
    const cellSize = api2.rendering.getGridMetrics().cellSize;
    const camera = state.session.camera;
    const damageLevel = api2.upgrades.getLevelById(itemId, damageUpgradeId);
    const damage = BASE_BEAM_DAMAGE + damagePerLevel * damageLevel;
    return {
      now,
      originX,
      originY,
      aimAngle,
      spread,
      spin,
      width,
      brightness,
      cellSize,
      camera,
      damage
    };
  }
  function getBeamAngle(index, frame) {
    const lane = (index - (config2.beamCount - 1) / 2) / ((config2.beamCount - 1) / 2);
    const wobble = Math.sin(frame.spin + index * Math.PI * 2 / config2.beamCount) * frame.spread * 0.25;
    return frame.aimAngle + lane * frame.spread + wobble;
  }
  function createImpact(index, hit, endX, endY, angle, color, frame) {
    const outVelocity = {
      x: 300 * Math.cos(angle),
      y: 300 * -Math.sin(angle)
    };
    api2.patterns.excavateAtCell(
      hit.x,
      hit.y,
      excavationPattern2,
      outVelocity,
      frame.damage,
      { fromDrill: true }
    );
    api2.effects.createLightAtWorld(endX, endY, {
      brightness: frame.brightness,
      duration: 300,
      size: 300,
      color: hexToLightColor(color),
      dedupKey: `last-prism:impact:${index}`
    });
    api2.effects.createParticlesAtWorld(endX, endY, {
      count: 8,
      minSpeed: 100,
      maxSpeed: 200,
      color,
      minSize: 1,
      maxSize: 2,
      minLifetime: 0.2,
      maxLifetime: 0.4
    });
  }
  function createBeam(index, frame) {
    const angle = getBeamAngle(index, frame);
    const hit = api2.raycast.castFromWorld(
      frame.originX,
      frame.originY,
      angle,
      config2.maxRangePx
    );
    const endX = hit ? hit.x * frame.cellSize : frame.originX + Math.cos(angle) * config2.maxRangePx;
    const endY = hit ? hit.y * frame.cellSize : frame.originY + Math.sin(angle) * config2.maxRangePx;
    const color = hueToHex(
      frame.now * 360 / COLOR_CYCLE_MS + index * 360 / config2.beamCount
    );
    beamGraphics.push(
      api2.effects.createLaserAtWorld(
        frame.originX - frame.camera.x,
        frame.originY - frame.camera.y,
        endX - frame.camera.x,
        endY - frame.camera.y,
        { width: frame.width, brightness: frame.brightness, color, glow: true }
      )
    );
    if (!hit) {
      return false;
    }
    createImpact(index, hit, endX, endY, angle, color, frame);
    return true;
  }
  function renderBeams(state, now) {
    const frame = getBeamFrame(state, now);
    let hitAnything = false;
    for (let index = 0; index < config2.beamCount; index += 1) {
      hitAnything = createBeam(index, frame) || hitAnything;
    }
    api2.effects.createLightAtWorld(frame.originX, frame.originY, {
      brightness: 0.8 * frame.brightness,
      duration: 1,
      size: 300,
      color: [1, 1, 1, 1],
      dedupKey: "last-prism:origin"
    });
    if (hitAnything) {
      api2.sound.play("laser_hit", {
        playbackRate: api2.random.float(0.1, 1.5),
        volume: 0.02,
        maxInstances: 96
      });
    }
  }
  function handleAction(state) {
    destroyBeams();
    const actionState = state.session.action.state;
    if (!actionState[ActionState2.Active]) {
      resetCharge();
      return;
    }
    if (!api2.authorization.canUseTool(state.store.player)) {
      if (actionState[ActionState2.Start]) {
        api2.ui.toast("Last Prism cannot be used here");
      }
      resetCharge();
      return;
    }
    const now = api2.time.getTimeMs();
    if (actionState[ActionState2.Start]) {
      startCharge(now);
    }
    renderBeams(state, now);
  }
  return {
    handleAction
  };
}

// src/register.js
function registerLastPrism({
  api: api2,
  sandkit: sandkit2,
  lastPrism: lastPrism2,
  itemId,
  damageUpgradeId,
  damagePerLevel,
  thicknessUpgradeId,
  thicknessPerLevelPercent
}) {
  api2.i18n.register("en", {
    "items|paragax.lastPrism|name": "Last Prism",
    "items|paragax.lastPrism|description": "Channels six converging rainbow lasers through hard materials.",
    "mods|paragax.lastPrism|upgrade|damage|name": "Prismatic Damage",
    "mods|paragax.lastPrism|upgrade|damage|description": "Increases terrain damage from each laser (+{amount} per level).",
    "mods|paragax.lastPrism|upgrade|thickness|name": "Beam Thickness",
    "mods|paragax.lastPrism|upgrade|thickness|description": "Increases thickness of each beam (+{percent}% per level)."
  });
  api2.items.register(lastPrism2);
  api2.upgrades.register({
    itemId,
    itemNameKey: "items|paragax.lastPrism|name",
    categoryId: "tools",
    upgrade: {
      id: damageUpgradeId,
      nameKey: "mods|paragax.lastPrism|upgrade|damage|name",
      descriptionKey: "mods|paragax.lastPrism|upgrade|damage|description",
      descriptionParams: { amount: damagePerLevel },
      maxLevel: 3,
      // TODO: Replace temporary zero upgrade costs after balance testing.
      costs: [0, 0, 0]
    }
  });
  api2.upgrades.register({
    itemId,
    upgrade: {
      id: thicknessUpgradeId,
      nameKey: "mods|paragax.lastPrism|upgrade|thickness|name",
      descriptionKey: "mods|paragax.lastPrism|upgrade|thickness|description",
      descriptionParams: { percent: thicknessPerLevelPercent },
      maxLevel: 4,
      // TODO: Replace temporary zero upgrade costs after balance testing.
      costs: [0, 0, 0, 0]
    }
  });
  api2.events.on("game:started", () => {
    const inventory = sandkit2.engine.state?.store?.player?.inventory;
    if (!inventory?.some((item) => item.id === itemId)) {
      api2.player.inventory.addFromId(itemId);
      api2.ui.toast("Last Prism added to inventory");
    }
  });
  console.info("[Last Prism] registered");
}

// src/main.js
var api = sandkit.api;
var { ActionState } = sandkit.enums;
var ITEM_ID = "paragax.last-prism";
var SPRITE_ID = "paragax.last-prism.sprite";
var SPRITE_SIZE = { width: 26, height: 30 };
var NATIVE_WINDUP_MS = 1e3;
var NATIVE_RANGE_PX = 1e3;
var BEAM_COUNT = 6;
var MAX_SPREAD_RADIANS = Math.PI / 12;
var DAMAGE_UPGRADE_ID = "damage";
var DAMAGE_PER_LEVEL = 1;
var THICKNESS_UPGRADE_ID = "thickness";
var THICKNESS_PER_LEVEL_PERCENT = 100;
var nativeLaser = api.items.getDefinitionById("laser");
if (!nativeLaser) {
  throw new Error("[Last Prism] Native laser definition was not found");
}
await api.sprites.loadFromMod(
  SPRITE_ID,
  "assets/last-prism.png"
);
var config = {
  ...nativeLaser.config,
  // TODO: Add a real energy cost after balance testing.
  energyCost: 0,
  windupMs: NATIVE_WINDUP_MS,
  maxRangePx: NATIVE_RANGE_PX,
  beamCount: BEAM_COUNT,
  maxSpreadRadians: MAX_SPREAD_RADIANS
};
var excavationPattern = api.patterns.createCircle(
  config.normalPatternSize
);
var beamController = createBeamController(
  api,
  ActionState,
  config,
  excavationPattern,
  ITEM_ID,
  DAMAGE_UPGRADE_ID,
  DAMAGE_PER_LEVEL,
  THICKNESS_UPGRADE_ID,
  THICKNESS_PER_LEVEL_PERCENT
);
var lastPrism = {
  ...nativeLaser,
  id: ITEM_ID,
  nameKey: "items|paragax.lastPrism|name",
  descriptionKey: "items|paragax.lastPrism|description",
  sprite: {
    ...nativeLaser.sprite,
    id: SPRITE_ID,
    ui: {
      ...nativeLaser.sprite.ui,
      imageName: SPRITE_ID,
      // Hotbar rendering otherwise assumes a 16x16 source rectangle.
      size: SPRITE_SIZE
    }
  },
  config,
  handleAction: beamController.handleAction,
  afterRender: () => {
  }
};
registerLastPrism({
  api,
  sandkit,
  lastPrism,
  itemId: ITEM_ID,
  damageUpgradeId: DAMAGE_UPGRADE_ID,
  damagePerLevel: DAMAGE_PER_LEVEL,
  thicknessUpgradeId: THICKNESS_UPGRADE_ID,
  thicknessPerLevelPercent: THICKNESS_PER_LEVEL_PERCENT
});
